{% set name = "alchemlyb" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alchemlyb-{{ version }}.tar.gz
  sha256: 4a9e243a446e3f6ef7ee8afa4c4ef35e63148ab8501737d48df54077289083c1

build:
  noarch: python
  number: 1

test:
  imports:
    - alchemlyb
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: {{ name }}-core
    script: python -m pip install . -vv
    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - loguru
        - matplotlib-base
        - numpy
        - pandas >=1.4
        - pyarrow
        - pymbar-core >=4
        - python >=3.8
        - scikit-learn
        - scipy

  - name: {{ name }}
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('alchemlyb-core', exact=True) }}
        - pymbar >=4

about:
  home: https://github.com/alchemistry/alchemlyb
  summary: the simple alchemistry library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - orbeckst
    - jan-janssen
