{% set name = "alchemlyb" %}
{% set version = "2.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alchemlyb-{{ version }}.tar.gz
  sha256: d360fca39d0e6a9d85744413be4b1794dfd448c5558a145e975f71ce7a8da48b

# We skip the top-level build because the actual build commands are defined in the 'outputs'.
# This prevents conda-build from creating a top-level package with no content.
build:
  number: 1
  skip: true

outputs:
  - name: {{ name }}-core
    # This is the core package that contains all the code.
    # The build script is run here to install the Python library.
    script: {{ PYTHON }} -m pip install . -vv
    build:
      noarch: python

    requirements:
      host:
        - pip
        - setuptools
        - python >=3.10
      run:
        - loguru
        - matplotlib-base >=3.7
        - numpy
        - pandas >=2.1
        - pyarrow
        - pymbar-core >=4  # Core dependency
        - python >=3.10
        - scikit-learn
        - scipy

    # The test for the core package can just be the import.
    test:
      imports:
        - alchemlyb

  - name: {{ name }}
    # This is a metapackage. It has no build script and contains no files.
    # Its purpose is to depend on the '-core' package and add the full 'pymbar'.
    build:
      noarch: python

    requirements:
      run:
        # This special syntax ensures that installing 'alchemlyb' will pull in the
        # 'alchemlyb-core' package that was built at the exact same time.
        - {{ pin_subpackage('alchemlyb-core', exact=True) }}
        - pymbar >=4  # The full pymbar dependency is added here.
        - python >=3.10

    # The test for this metapackage ensures that after installation,
    # the environment is consistent.
    test:
      imports:
        - alchemlyb
      commands:
        - pip check
      requires:
        - pip

# The 'about' and 'extra' sections are common to all packages built from this recipe.
about:
  home: https://github.com/alchemistry/alchemlyb
  summary: the simple alchemistry library
  description: |
    alchemlyb is an open-source Python software package for
    the analysis of alchemical free energy calculations. Its
    functionality contains individual composable building
    blocks for all aspects of a full typical free energy
    analysis workflow, starting with the extraction of raw
    data from the output of diverse molecular simulation
    packages, moving on to data preprocessing tasks such as
    decorrelation of time series, using various estimators to
    derive free energy estimates from simulation samples, and
    finally providing quality analysis tools for data
    convergence checking and visualization. alchemlyb also
    contains high-level end-to-end workflows that combine
    multiple building blocks into a user-friendly analysis
    pipeline from the initial data input stage to the final
    results.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/alchemistry/alchemlyb
  doc_url: https://alchemlyb.readthedocs.io/

extra:
  recipe-maintainers:
    - xiki-tempula
    - orbeckst
    - jan-janssen
