{% set name = "alchemlyb" %}
{% set version = "2.4.1" %}
# set minimal Python version from
# https://github.com/alchemistry/alchemlyb/blob/master/pyproject.toml#L42
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alchemlyb-{{ version }}.tar.gz
  sha256: d360fca39d0e6a9d85744413be4b1794dfd448c5558a145e975f71ce7a8da48b

build:
  number: 0

outputs:
  - name: {{ name }}-core
    build:
      noarch: python
    requirements:
      host:
        - pip
        # Pin to the specific minimum Python version for the build environment
        - python {{ python_min }}
        - setuptools
      run:
        - loguru
        - matplotlib-base >=3.7
        - numpy
        - pandas >=2.1
        - pyarrow
        - pymbar-core >=4
        # The run requirement correctly allows for any newer Python version
        - python >={{ python_min }}
        - scikit-learn
        - scipy
    test:
      imports:
        - alchemlyb

  - name: {{ name }}
    build:
      noarch: python
    requirements:
      host:
        # Pin to the specific minimum Python version
        - python {{ python_min }}
      run:
        - {{ pin_subpackage("alchemlyb-core", exact=True) }}
        - pymbar >=4
        - python >={{ python_min }}
    test:
      requires:
        - pip
        # Pin to the specific minimum Python version for the test environment
        - python {{ python_min }}
      imports:
        - alchemlyb
      commands:
        - pip check

about:
  home: https://github.com/alchemistry/alchemlyb
  summary: the simple alchemistry library
  description: |
    alchemlyb is an open-source Python software package for
    the analysis of alchemical free energy calculations. Its
    functionality contains individual composable building
    blocks for all aspects of a full typical free energy
    analysis workflow, starting with the extraction of raw
    data from the output of diverse molecular simulation
    packages, moving on to data preprocessing tasks such as
    decorrelation of time series, using various estimators to
    derive free energy estimates from simulation samples, and
    finally providing quality analysis tools for data
    convergence checking and visualization. alchemlyb also
    contains high-level end-to-end workflows that combine
    multiple
