{% set name = "alchemlyb" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alchemlyb-{{ version }}.tar.gz
  sha256: b617da4bba714f14bcb2db727be981fd0fb60c250b523876dd902d1249ef8533

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - loguru
    - matplotlib-base >=3.7
    - numpy
    - pandas >=1.4
    - pyarrow
    - pymbar >=4
    - python >=3.8
    - scikit-learn
    - scipy

test:
  imports:
    - alchemlyb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alchemistry/alchemlyb
  summary: the simple alchemistry library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - orbeckst
    - jan-janssen
