{% set name = "alchemlyb" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alchemlyb-{{ version }}.tar.gz
  sha256: b617da4bba714f14bcb2db727be981fd0fb60c250b523876dd902d1249ef8533

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - setuptools
    - python >=3.10
  run:
    - loguru
    - matplotlib-base >=3.7
    - numpy
    - pandas >=2.1
    - pyarrow
    - pymbar >=4
    - python >=3.10
    - scikit-learn
    - scipy

test:
  imports:
    - alchemlyb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alchemistry/alchemlyb
  summary: the simple alchemistry library
  description: |
      alchemlyb is an open-source Python software package for
      the analysis of alchemical free energy calculations. Its
      functionality contains individual composable building
      blocks for all aspects of a full typical free energy
      analysis workflow, starting with the extraction of raw
      data from the output of diverse molecular simulation
      packages, moving on to data preprocessing tasks such as
      decorrelation of time series, using various estimators to
      derive free energy estimates from simulation samples, and
      finally providing quality analysis tools for data
      convergence checking and visualization. alchemlyb also
      contains high-level end-to-end workflows that combine
      multiple building blocks into a user-friendly analysis
      pipeline from the initial data input stage to the final
      results.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/alchemistry/alchemlyb
  doc_url: https://alchemlyb.readthedocs.io/

extra:
  recipe-maintainers:
    - xiki-tempula
    - orbeckst
    - jan-janssen
